### PR TITLE
Fix NullReferenceException in NestedMarkupExtension

### PR DESCRIPTION
**Pull request by mark-monteiro**
Attempt to fix https://github.com/XAMLMarkupExtensions/WPFLocalizationExtension/issues/296

I didn't spend any time testing this, it's just a quick edit I threw together in GitHub that looks like it should fix the issue based on the research provided by the creator of the issue.

Feel free to make any changes as necessary or let me know if there's any changes you'd like me to make myself.

### CODE REVIEW

**Comment by ruudsieb** [comment]
Is this going to be merged any time soon?

**Comment by konne** [comment]
@mark-monteiro @ruudsieb 
this is already fixed via another PR. I will close this PR and try to make a release in the next days

**Comment by konne** [comment]
@mark-monteiro @ruudsieb 
the is a new 3.8.1-preview of the WPFLocExt that should work.
Please test

**Comment by mark-monteiro** [comment]
@konne I've been running with the pre-release for a couple days and haven't noticed any regressions. The `NullReferenceException` in the designer appears to be fixed as well. Thanks!

**Pull request closed without merging**
